# Copyright (c) 2024 Reciprocal Space Ship
# SPDX-License-Identifier: MIT

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
